server:
  port: 9191
  
spring:
   application:
      name: API-GATEWAY
   cloud:
       gateway:
         routes:
         - id: auth-service
           uri: lb://auth-service#lb = load balancer
           predicates:
            - Path=/users/**
         - id: advertise-service
           uri: lb://advertise-service
           predicates:
            - Path=/olx-adv/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}